# entity : ZOMBIE, SKELETON, BAT, SPIDER, CREEPER, ENDERMAN, WITCH, SLIME, GHAST, PIGMAN, BLAZE, MAGMA_CUBE, SILVERFISH, WITHER_SKELETON, WITHER, ENDER_DRAGON, GIANT, IRON_GOLEM, SNOWMAN, VILLAGER, WOLF, OCELOT, HORSE, RABBIT, SHEEP, PIG, COW, CHICKEN, SQUID, BAT, VILLAGER,

entity:
  zombie:
    type: ZOMBIE
    name: "§6§lTapTycoon"
    health: 100
    levelrequired: 0
    glowing: true
    moneyrange:
        min: 1
        max: 10

